#!/usr/bin/env node
/**
 * Uploads the local "ganpati photos" and "vpl photos" folders to Cloudinary
 * and writes the resulting secure URLs into frontend/src/data/galleries.js.
 *
 * Credentials are read from environment variables (put them in backend/.env or
 * export them in your shell before running):
 *
 *   CLOUDINARY_CLOUD_NAME   (required)
 *   CLOUDINARY_API_KEY      (required for signed upload)
 *   CLOUDINARY_API_SECRET   (required for signed upload)
 *
 * Run from the repo root:
 *   node --env-file=backend/.env scripts/uploadToCloudinary.mjs
 */
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { basename, extname, join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

const CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const API_KEY = process.env.CLOUDINARY_API_KEY;
const API_SECRET = process.env.CLOUDINARY_API_SECRET;
const UPLOAD_PRESET = process.env.CLOUDINARY_UPLOAD_PRESET; // optional: enables unsigned upload

const UNSIGNED = Boolean(UPLOAD_PRESET);

if (!CLOUD_NAME || (!UNSIGNED && (!API_KEY || !API_SECRET))) {
  console.error('Missing Cloudinary config.');
  console.error('Signed:   set CLOUDINARY_CLOUD_NAME + CLOUDINARY_API_KEY + CLOUDINARY_API_SECRET');
  console.error('Unsigned: set CLOUDINARY_CLOUD_NAME + CLOUDINARY_UPLOAD_PRESET');
  console.error('Then run: node --env-file=backend/.env scripts/uploadToCloudinary.mjs');
  process.exit(1);
}
console.log(`Mode: ${UNSIGNED ? `unsigned (preset "${UPLOAD_PRESET}")` : 'signed (api key)'} | cloud: ${CLOUD_NAME}`);

const IMAGE_EXT = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif']);

const GROUPS = [
  { dir: 'ganpati photos', folder: 'vijaywalunj/ganpati', varName: 'GANPATI_PHOTOS', caption: 'Ganraj Vashicha' },
  { dir: 'vpl photos', folder: 'vijaywalunj/vpl', varName: 'VPL_PHOTOS', caption: 'Vashi Premier League' },
];

const sign = (params) => {
  const toSign = Object.keys(params)
    .sort()
    .map((k) => `${k}=${params[k]}`)
    .join('&');
  return createHash('sha1').update(toSign + API_SECRET).digest('hex');
};

const uploadFile = async (filePath, folder) => {
  // Stable public_id (folder + sanitized filename) so re-runs overwrite instead of duplicating.
  const publicId = basename(filePath, extname(filePath)).replace(/[^a-zA-Z0-9_-]/g, '_');

  const form = new FormData();
  const bytes = await readFile(filePath);
  form.append('file', new Blob([bytes]), basename(filePath));
  form.append('folder', folder);
  form.append('public_id', publicId);

  if (UNSIGNED) {
    form.append('upload_preset', UPLOAD_PRESET);
  } else {
    const timestamp = Math.round(Date.now() / 1000);
    form.append('api_key', API_KEY);
    form.append('timestamp', String(timestamp));
    form.append('signature', sign({ folder, public_id: publicId, timestamp }));
  }

  const res = await fetch(`https://api.cloudinary.com/v1_1/${CLOUD_NAME}/image/upload`, {
    method: 'POST',
    body: form,
  });
  const json = await res.json();
  if (!res.ok) {
    throw new Error(json?.error?.message || `Upload failed (${res.status}) for ${basename(filePath)}`);
  }
  return json.secure_url;
};

const results = {};

for (const group of GROUPS) {
  const abs = join(ROOT, group.dir);
  let files = [];
  try {
    files = (await readdir(abs))
      .filter((f) => IMAGE_EXT.has(extname(f).toLowerCase()))
      .sort();
  } catch {
    console.warn(`Folder not found, skipping: ${group.dir}`);
    results[group.varName] = [];
    continue;
  }

  console.log(`\nUploading ${files.length} file(s) from "${group.dir}" -> ${group.folder}`);
  const urls = [];
  for (let i = 0; i < files.length; i += 1) {
    const file = files[i];
    process.stdout.write(`  [${i + 1}/${files.length}] ${file} ... `);
    try {
      const url = await uploadFile(join(abs, file), group.folder);
      urls.push({ url, caption: `${group.caption} ${i + 1}` });
      console.log('ok');
    } catch (err) {
      console.log(`FAILED: ${err.message}`);
    }
  }
  results[group.varName] = urls;
}

// Write galleries.js
const serialize = (arr) => {
  if (!arr.length) return '[]';
  const items = arr
    .map((it) => `  { url: '${it.url}', caption: ${JSON.stringify(it.caption)} },`)
    .join('\n');
  return `[\n${items}\n]`;
};

const out = `// Slideshow images hosted on Cloudinary.
// Each entry: { url, caption }
// Auto-generated by scripts/uploadToCloudinary.mjs — re-run that script to refresh.

export const GANPATI_PHOTOS = ${serialize(results.GANPATI_PHOTOS || [])};

export const VPL_PHOTOS = ${serialize(results.VPL_PHOTOS || [])};
`;

await writeFile(join(ROOT, 'frontend/src/data/galleries.js'), out, 'utf8');
console.log('\nWrote frontend/src/data/galleries.js');
console.log(`  GANPATI_PHOTOS: ${(results.GANPATI_PHOTOS || []).length}`);
console.log(`  VPL_PHOTOS: ${(results.VPL_PHOTOS || []).length}`);
